apiVersion: batch/v1
kind: CronJob
metadata:
  name: densify-optimizer-job
  namespace: densify
spec:
  # every night @ 8pm
  schedule: "0 20 * * *"
  # every 1 hour (for testing only)
  # schedule: "0 * * * *"
  # every 5 minutes (for testing only)
  # schedule: "*/5 * * * *"
  # every 1 minute (for testing only)
  # schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: ssvyper/densify-optimizer:latest
            args:
            # - -c=/config/densify-optimizer-config.properties
            imagePullPolicy: Always
            name: densify-optimizer
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            volumeMounts:
            - mountPath: /config
              name: densify-optimizer-config
              readOnly: true
            - mountPath: /data-export
              name: densify-data-export
          volumes:
          - name: densify-optimizer-config
            configMap:
              name: densify-optimizer-config
              items:
                - key: densify-optimizer-config.properties
                  path: densify-optimizer-config.properties
          - name: densify-data-export
            persistentVolumeClaim:
                claimName: densify-volume-claim
          restartPolicy: OnFailure