# https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: densify-annotations
rules:
# see here for more info (/apis/*/): https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md
# k8s apis we use: CoreV1Api (pods), AppsV1Api (deployment, replicaset, daemonset, statefulset), BatchV1Api (cronjob, job)
- apiGroups: ["", "apps", "batch"]
  # k8s objects
  resources: ["pods","deployments","replicasets","statefulsets","daemonsets", "cronjobs", "jobs"]
  # k8s permissions
  verbs: ["get", "list", "patch"]
  # verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
