apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: densify-annotations
subjects:
- kind: ServiceAccount
  name: default
  namespace: densify
roleRef:
  kind: ClusterRole
  name: densify-annotations
  apiGroup: rbac.authorization.k8s.io
