apiVersion: v1
kind: PersistentVolume
metadata:
  name: densify-volume
  namespace: densify
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/densify"