apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: densify-volume-claim
  namespace: densify
spec:
  volumeName: densify-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: default